# Generated by Django 5.2.3 on 2025-06-26 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bracelet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='bracelets/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GemstoneSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rudraksha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mukhi', models.PositiveIntegerField(choices=[(1, '1 Mukhi'), (2, '2 Mukhi'), (3, '3 Mukhi'), (4, '4 Mukhi'), (5, '5 Mukhi'), (6, '6 Mukhi'), (7, '7 Mukhi'), (8, '8 Mukhi'), (9, '9 Mukhi'), (10, '10 Mukhi'), (11, '11 Mukhi'), (12, '12 Mukhi'), (13, '13 Mukhi'), (14, '14 Mukhi'), (15, '15 Mukhi')], unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('origin', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='rudraksha/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gemstone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
                ('base_price_per_carat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='gemstones/')),
                ('description', models.TextField(blank=True, null=True)),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gemstones', to='product.gemstonesubcategory')),
            ],
        ),
        migrations.CreateModel(
            name='GemstoneVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('gemstone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product.gemstone')),
            ],
            options={
                'unique_together': {('gemstone', 'carat')},
            },
        ),
    ]
