# Generated by Django 5.2.3 on 2025-06-28 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GemstoneType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Bracelet',
        ),
        migrations.DeleteModel(
            name='Rudraksha',
        ),
        migrations.AlterUniqueTogether(
            name='gemstonevariant',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='gemstone',
            name='name',
        ),
        migrations.AddField(
            model_name='gemstonesubcategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='product.maincategory'),
        ),
        migrations.AddField(
            model_name='gemstonevariant',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='gemstone_variants/'),
        ),
        migrations.AddField(
            model_name='gemstonevariant',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='gemstone_variants/'),
        ),
        migrations.AlterField(
            model_name='gemstonesubcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gemstonevariant',
            name='price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='gemstone',
            name='gemstone_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.gemstonetype'),
        ),
    ]
