# Generated by Django 5.2.3 on 2025-06-28 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_gemstonetype_delete_bracelet_delete_rudraksha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gemstonetype',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
