# Generated by Django 5.2.3 on 2025-06-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_gemstonetype_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rudraksha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('origin', models.CharField(max_length=100)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='rudraksha/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='rudraksha/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='rudraksha/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='rudraksha/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='rudraksha/')),
            ],
        ),
        migrations.AlterField(
            model_name='gemstonesubcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
