# Generated by Django 5.2.3 on 2025-06-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rudraksha_alter_gemstonesubcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gemstonesubcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
