# Generated by Django 5.2.3 on 2025-07-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_gemstonesubcategory_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bracelet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='bracelets/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='bracelets/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='bracelets/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='bracelets/')),
            ],
        ),
    ]
