# Generated by Django 5.2.3 on 2025-07-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_bracelet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gemstone',
            name='description',
        ),
        migrations.RemoveField(
            model_name='gemstone',
            name='gemstone_type',
        ),
        migrations.RemoveField(
            model_name='gemstone',
            name='image',
        ),
        migrations.RemoveField(
            model_name='gemstonevariant',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='gemstonevariant',
            name='image_2',
        ),
        migrations.AddField(
            model_name='gemstone',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gemstone',
            name='origin_image',
            field=models.ImageField(blank=True, null=True, upload_to='gemstones/origin/'),
        ),
    ]
