# Generated by Django 5.2.3 on 2025-07-05 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_gemstone_gemstone_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
