# Generated by Django 5.2.3 on 2025-07-07 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_cart_cartitem'),
        ('product', '0010_delete_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='gemstoneVariant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variant_cart_items', to='product.bracelet'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='bracelet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bracelet_cart_items', to='product.bracelet'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='gemstone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='product.gemstone'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='rudraksha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='product.rudraksha'),
        ),
    ]
