# Generated by Django 5.2.3 on 2025-07-07 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_cartitem_gemstonevariant_alter_cartitem_bracelet_and_more'),
        ('product', '0010_delete_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='gemstoneVariant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variant_cart_items', to='product.gemstonevariant'),
        ),
    ]
